apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::499439044679:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn:  arn:aws:iam::499439044679:role/eksctl-simple-jwt-api-nodegroup-ng-52704f13
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
