apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::brettjaybrewster@gmail.com:role/UdacityFlaskDeployCBKubectlRole
      username: build
      - rolearn: arn:aws:iam::brettjaybrewster@gmail.com:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-24T17:42:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12615"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 19435eed-572d-11ea-9d67-02ab0a44b4ae
