apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam:brettjaybrewster@gmail.com:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam:brettjaybrewster@gmail.com:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Z111GAIV048V
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
